name: flutter_utils
repository: https://github.com/erfactor/flutter_utils
version: 1.0.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: any
  hooks_riverpod: any
  dartx: any
  dio: ^5.9.0
  fpdart: ^1.2.0
  retrofit: ^4.9.2
  collection: ^1.19.1
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_lints: ^6.0.0
